const products = [
    {
      name: "Apple",
      category: "Fruit",
      id: 0,
      description:
        "A round fruit with a red, green, or yellow skin and a white, crunchy interior.",
      price: 89,
      rating: 5,
      discount: 0,
      image: "https://picsum.photos/200/300/?food0",
    },
    {
      name: "Banana",
      category: "Fruit",
      id: 1,
      description:
        "A long, curved fruit with a yellow skin and sweet, creamy white flesh.",
      price: 71,
      rating: 5,
      discount: 20,
      image: "https://picsum.photos/200/300/?food1",
    },
    {
      name: "Bread",
      category: "Bakery",
      id: 2,
      description:
        "A staple food made from flour, water, and yeast, baked into a loaf.",
      price: 88,
      rating: 5,
      discount: 20,
      image: "https://picsum.photos/200/300/?food2",
    },
    {
      name: "Broccoli",
      category: "Vegetable",
      id: 3,
      description:
        "A green vegetable with a tree-like appearance, known for its high nutrient content.",
      price: 94,
      rating: 4.5,
      discount: 20,
      image: "https://picsum.photos/200/300/?food3",
    },
    {
      name: "Carrot",
      category: "Vegetable",
      id: 4,
      description:
        "A root vegetable with a crunchy texture and a sweet, earthy flavor.",
      price: 82,
      rating: 5,
      discount: 20,
      image: "https://picsum.photos/200/300/?food4",
    },
    {
      name: "Cheese",
      category: "Dairy",
      id: 5,
      description:
        "A dairy product made from milk, with a variety of textures and flavors.",
      price: 91,
      rating: 3.5,
      discount: 50,
      image: "https://picsum.photos/200/300/?food5",
    },
    {
      name: "Chicken",
      category: "Meat",
      id: 6,
      description:
        "A type of poultry, often used as a source of protein in meals.",
      price: 68,
      rating: 3.5,
      discount: 20,
      image: "https://picsum.photos/200/300/?food6",
    },
    {
      name: "Chocolate",
      category: "Dessert",
      id: 7,
      description:
        "A sweet food made from cacao beans, used in a variety of desserts and confections.",
      price: 61,
      rating: 4.5,
      discount: 20,
      image: "https://picsum.photos/200/300/?food7",
    },
    {
      name: "Coffee",
      category: "Dessert",
      id: 8,
      description:
        "A dark, bitter beverage made from roasted coffee beans, typically used as a pick-me-up.",
      price: 98,
      rating: 5,
      discount: 20,
      image: "https://picsum.photos/200/300/?food8",
    },
    {
      name: "Egg",
      category: "Dairy",
      id: 9,
      description:
        "A oval-shaped reproductive body produced by birds, often used as a source of protein in meals.",
      price: 79,
      rating: 4.5,
      discount: 0,
      image: "https://picsum.photos/200/300/?food9",
    },
    {
      name: "Fish",
      category: "Meat",
      id: 10,
      description:
        "A type of seafood, known for its omega-3 fatty acids and high protein content.",
      price: 89,
      rating: 3.5,
      discount: 50,
      image: "https://picsum.photos/200/300/?food10",
    },
    {
      name: "Grapes",
      category: "Fruit",
      id: 11,
      description:
        "A small, sweet fruit that grows in clusters, often used in wine-making.",
      price: 61,
      rating: 4,
      discount: 20,
      image: "https://picsum.photos/200/300/?food11",
    },
    {
      name: "Hamburger",
      category: "Fast food",
      id: 12,
      description:
        "A sandwich made with a patty of ground beef, served on a bun with various toppings.",
      price: 87,
      rating: 5,
      discount: 0,
      image: "https://picsum.photos/200/300/?food12",
    },
    {
      name: "Hot dog",
      category: "Fast food",
      id: 13,
      description:
        "A type of sausage served in a long roll, often used as a quick and convenient food.",
      price: 84,
      rating: 4.5,
      discount: 50,
      image: "https://picsum.photos/200/300/?food13",
    },
    {
      name: "Ice cream",
      category: "Dessert",
      id: 14,
      description:
        "A frozen dessert made from cream, sugar, and flavorings, available in a variety of flavors.",
      price: 68,
      rating: 4.5,
      discount: 0,
      image: "https://picsum.photos/200/300/?food14",
    },
    {
      name: "Lemon",
      category: "Fruit",
      id: 15,
      description:
        "A yellow citrus fruit with a tart, acidic flavor, often used in cooking and baking.",
      price: 74,
      rating: 3.5,
      discount: 0,
      image: "https://picsum.photos/200/300/?food15",
    },
    {
      name: "Eggs",
      category: "Dairy",
      id: 16,
      description:
        "Eggs are oval-shaped reproductive structures produced by female birds and some reptiles.",
      price: 70,
      rating: 4.5,
      discount: 50,
      image: "https://picsum.photos/200/300/?food16",
    },
    {
      name: "Honey",
      category: "Dairy",
      id: 17,
      description:
        "Honey is a sweet, sticky liquid made by bees from the nectar of flowers.",
      price: 87,
      rating: 4,
      discount: 0,
      image: "https://picsum.photos/200/300/?food17",
    },
    {
      name: "Ice Cream",
      category: "Dessert",
      id: 18,
      description:
        "Ice cream is a frozen dessert made from cream, sugar, and flavorings.",
      price: 83,
      rating: 4.5,
      discount: 0,
      image: "https://picsum.photos/200/300/?food18",
    },
    {
      name: "Jelly",
      category: "Fruit",
      id: 19,
      description:
        "Jelly is a sweet spread made from fruit juice and sugar, often used as a topping for toast or pastries.",
      price: 76,
      rating: 5,
      discount: 0,
      image: "https://picsum.photos/200/300/?food19",
    },
    {
      name: "Ketchup",
      category: "Dairy",
      id: 20,
      description:
        "Ketchup is a tangy sauce made from tomatoes, vinegar, sugar, and spices.",
      price: 77,
      rating: 5,
      discount: 0,
      image: "https://picsum.photos/200/300/?food20",
    },
    {
      name: "Mango",
      category: "Fruit",
      id: 21,
      description:
        "Mangoes are juicy, sweet tropical fruits with a fleshy interior and a large, oblong seed in the center.",
      price: 80,
      rating: 5,
      discount: 20,
      image: "https://picsum.photos/200/300/?food21",
    },
    {
      name: "Noodles",
      category: "Meat",
      id: 22,
      description:
        "Noodles are a type of pasta made from wheat flour and water, often used in Asian cuisine.",
      price: 93,
      rating: 3.5,
      discount: 20,
      image: "https://picsum.photos/200/300/?food22",
    },
    {
      name: "Oatmeal",
      category: "Breakfast",
      id: 23,
      description:
        "Oatmeal is a type of porridge made from oats that is often served for breakfast.",
      price: 94,
      rating: 4.5,
      discount: 0,
      image: "https://picsum.photos/200/300/?food23",
    },
    {
      name: "Bacon",
      category: "Breakfast",
      id: 24,
      description:
        "Bacon is a popular breakfast food made from cured pork belly.",
      price: 71,
      rating: 3.5,
      discount: 20,
      image: "https://picsum.photos/200/300/?food24",
    },
    {
      name: "Pancakes",
      category: "Breakfast",
      id: 25,
      description:
        "Pancakes are a popular breakfast food made from flour, eggs, and milk.",
      price: 63,
      rating: 4,
      discount: 0,
      image: "https://picsum.photos/200/300/?food25",
    },
    {
      name: "Waffles",
      category: "Breakfast",
      id: 26,
      description:
        "Waffles are a type of breakfast food made from batter cooked in a waffle iron.",
      price: 97,
      rating: 4.5,
      discount: 20,
      image: "https://picsum.photos/200/300/?food26",
    },
    {
      name: "Fried Rice",
      category: "Lunch",
      id: 27,
      description:
        "Fried Rice is a type of rice dish that is stir-fried in a pan with oil and other ingredients.",
      price: 81,
      rating: 4,
      discount: 20,
      image: "https://picsum.photos/200/300/?food27",
    },
    {
      name: "Spaghetti",
      category: "Lunch",
      id: 28,
      description:
        "Spaghetti is a type of pasta made from wheat flour and water, usually served with sauce.",
      price: 96,
      rating: 4,
      discount: 50,
      image: "https://picsum.photos/200/300/?food28",
    },
    {
      name: "Pizza",
      category: "Lunch",
      id: 29,
      description:
        "Pizza is a popular dish made from dough, sauce, cheese, and toppings.",
      price: 95,
      rating: 4,
      discount: 0,
      image: "https://picsum.photos/200/300/?food29",
    },
    {
      name: "Grilled Cheese",
      category: "Lunch",
      id: 30,
      description:
        "A grilled cheese sandwich is a hot sandwich made from cheese and bread.",
      price: 100,
      rating: 5,
      discount: 50,
      image: "https://picsum.photos/200/300/?food30",
    },
    {
      name: "Steak",
      category: "Dinner",
      id: 31,
      description:
        "Steak is a popular dinner dish made from a cut of beef that is usually grilled or pan-fried.",
      price: 63,
      rating: 4.5,
      discount: 20,
      image: "https://picsum.photos/200/300/?food31",
    },
    {
      name: "Salmon",
      category: "Dinner",
      id: 32,
      description:
        "Salmon is a type of fish that is often grilled or baked and served as a main course.",
      price: 82,
      rating: 4.5,
      discount: 20,
      image: "https://picsum.photos/200/300/?food32",
    },
    {
      name: "Chicken Alfredo",
      category: "Dinner",
      id: 33,
      description:
        "Chicken Alfredo is a pasta dish made with chicken, fettuccine pasta, and a creamy Alfredo sauce.",
      price: 94,
      rating: 4,
      discount: 20,
      image: "https://picsum.photos/200/300/?food33",
    },
    {
      name: "Lasagna",
      category: "Dinner",
      id: 34,
      description:
        "Lasagna is a type of pasta dish made with layers of pasta, sauce, cheese, and meat or vegetables.",
      price: 70,
      rating: 5,
      discount: 0,
      image: "https://picsum.photos/200/300/?food34",
    },
    {
      name: "Chocolate",
      category: "Dessert",
      id: 35,
      description:
        "Chocolate Chip Cookies are a type of cookie made from flour, sugar, butter, and chocolate chips.",
      price: 98,
      rating: 3.5,
      discount: 0,
      image: "https://picsum.photos/200/300/?food35",
    },
  ];